YOLOV3:
  CFG: "detector_YOLO_v3/YOLOv3/cfg/yolo_v3.cfg"
  WEIGHT: "detector_YOLO_v3/YOLOv3/weight/yolov3.weights"
  CLASS_NAMES: "detector_YOLO_v3/YOLOv3/cfg/coco.names"

  SCORE_THRESH: 0.3
  NMS_THRESH: 0.3
